export const GET_LIST_OF_PRODUCTS = 'GET_LIST_OF_PRODUCTS';
export const GET_ALL_IMAGES_FROM_STORAGE = 'GET_ALL_IMAGES_FROM_STORAGE';
export const GET_ORDER_LIST = 'GET_ORDER_LIST';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';